version: "3.9"

services:
  find_friend_db:
    container_name: find_friend_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:1234@find_friend_db:5432/postgres
    depends_on:
      - find_friend_db
    ports:
      - "8088:8088"

volumes:
  pgdata:
