version: "3.9"
services:
  find_friend_db:
    container_name: ${DB_NAME}
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: root
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  # app:
  #   build: .
  #   environment:
  #     DATABASE_URL: postgres://root:@find_friend_db:5432/find_friend_db
  #     WEB_SERVER_PORT: ${WEB_SERVER_PORT}
  #     JWT_SECRET: ${JWT_SECRET}
  #     JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
  #     STAGE: ${STAGE}
  #   depends_on:
  #     - find_friend_db
  #   ports:
  #     - "8088:8088"
volumes:
  pgdata:
