version: "3.9"
services:
  find_friend_db:
    container_name: find_friend_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - find_friend_db
    ports:
      - "8088:8088"
volumes:
  pgdata:
